export const subjects = [
  {
    id: "computer-science",
    name: "Computer Science",
    description: "Dive into the fundamentals of computing, algorithms, and software development.",
    icon: "Code",
    topics: [
      "Object-Oriented Programming",
      "Clean Code",
      "Data Structures",
      "Algorithms",
      "Design Patterns",
      "Software Architecture",
      "Version Control",
      "Testing and TDD",
      "Agile Methodologies",
    ],
  },
  {
    id: "web-development",
    name: "Web Development",
    description: "Learn to build modern, responsive web applications.",
    icon: "Globe",
    topics: [
      "HTML & CSS",
      "JavaScript",
      "React",
      "Node.js",
      "RESTful APIs",
      "GraphQL",
      "Web Security",
      "Performance Optimization",
      "Progressive Web Apps",
    ],
  },
  {
    id: "data-science",
    name: "Data Science",
    description: "Explore the world of data analysis, machine learning, and statistical modeling.",
    icon: "BarChart",
    topics: [
      "Python for Data Science",
      "Data Visualization",
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Big Data Technologies",
      "Statistical Analysis",
      "Data Ethics",
      "Time Series Analysis",
    ],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    description: "Learn about protecting computer systems and networks from cyber threats.",
    icon: "Shield",
    topics: [
      "Network Security",
      "Cryptography",
      "Ethical Hacking",
      "Security Policies",
      "Incident Response",
      "Malware Analysis",
      "Cloud Security",
      "IoT Security",
      "Cyber Law and Ethics",
    ],
  },
  {
    id: "mobile-development",
    name: "Mobile Development",
    description: "Build native and cross-platform mobile applications.",
    icon: "Smartphone",
    topics: [
      "iOS Development with Swift",
      "Android Development with Kotlin",
      "React Native",
      "Flutter",
      "Mobile UI/UX Design",
      "App Store Optimization",
      "Mobile Backend Services",
      "Push Notifications",
      "Mobile App Testing",
    ],
  },
]

